### ISSUE TITLE
The osd_memory_target parameter does not take effect

### ISSUE THREAD

**Issue by yule-sun** [ceph/git.ceph.com#1]
I used cephadm to deploy a pacific version of the cluster. I found that the memory limit for the osd container did not take effect. What should I do to adjust the memory usage of the osd container to make it comply with the osd_target_memory limit?

1.  ceph version
[root@zl-k8s-ceph72 zzcloud]# ceph -v
ceph version 16.2.9 (4c3647a322c0ff5a1dd2344e039859dcbd28c830) pacific (stable)

2. memory limit displayed by ceph orch ps
![image](https://user-images.githubusercontent.com/37107125/180904516-57cd6d7f-5863-4b85-934c-2f570f777bc2.png)

3. Memory usage shown by podman stats
![image](https://user-images.githubusercontent.com/37107125/180904555-d5c131aa-f4d5-46f5-b2e5-d8938ded3b1f.png)
As you can see from the above two figures, the memory limit in cephadm does not take effect in podman. Observe that the memory limit of the osd container is all the memory of the server. So what should I do instead to adjust the osd's memory cap?
Looking forward to your reply, thanks

**Comment by tchaikov** [comment]
@yule-sun git.ceph.com is not the best venue for filing cephadm issues, you might want to head over to https://tracker.ceph.com instead.

**Comment by yule-sun** [comment]
> 

Oh sorry, I will go to the url you sent to submit the question. Sorry for the inconvenience caused to you.
